-- CreateTable
CREATE TABLE `HOCKYNAMHOC` (
    `MaHKNH` VARCHAR(15) NOT NULL,
    `HocKy` VARCHAR(20) NOT NULL,
    `NgayBatDau` DATETIME(3) NOT NULL,
    `NgayKetThuc` DATETIME(3) NOT NULL,
    `HanDongHocPhi` DATETIME(3) NOT NULL,

    PRIMARY KEY (`MaHKNH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MONHOCMO` (
    `MaMonHocMo` VARCHAR(15) NOT NULL,
    `MaHKNH` VARCHAR(15) NOT NULL,
    `MaMonHoc` VARCHAR(10) NOT NULL,
    `SiSoToiDa` INTEGER NOT NULL DEFAULT 50,
    `SiSoHienTai` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `MONHOCMO_MaHKNH_MaMonHoc_key`(`MaHKNH`, `MaMonHoc`),
    PRIMARY KEY (`MaMonHocMo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MONHOCMO` ADD CONSTRAINT `MONHOCMO_MaHKNH_fkey` FOREIGN KEY (`MaHKNH`) REFERENCES `HOCKYNAMHOC`(`MaHKNH`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MONHOCMO` ADD CONSTRAINT `MONHOCMO_MaMonHoc_fkey` FOREIGN KEY (`MaMonHoc`) REFERENCES `MONHOC`(`MaMonHoc`) ON DELETE RESTRICT ON UPDATE CASCADE;
