-- CreateTable
CREATE TABLE `LOAIMONHOC` (
    `MaLoaiMonHoc` VARCHAR(10) NOT NULL,
    `TenLoaiMonHoc` VARCHAR(50) NOT NULL,
    `SoTietMotTinChi` INTEGER NOT NULL,
    `SoTienMotTinChi` DECIMAL(12, 2) NOT NULL,

    UNIQUE INDEX `LOAIMONHOC_TenLoaiMonHoc_key`(`TenLoaiMonHoc`),
    PRIMARY KEY (`MaLoaiMonHoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MONHOC` (
    `MaMonHoc` VARCHAR(10) NOT NULL,
    `TenMonHoc` VARCHAR(150) NOT NULL,
    `MaKhoa` VARCHAR(10) NOT NULL,
    `MaLoaiMonHoc` VARCHAR(10) NOT NULL,
    `SoTiet` INTEGER NOT NULL,

    UNIQUE INDEX `MONHOC_TenMonHoc_key`(`TenMonHoc`),
    PRIMARY KEY (`MaMonHoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CT_MONHOCTRUOC` (
    `MaMonHoc` VARCHAR(10) NOT NULL,
    `MaMonHocTruoc` VARCHAR(10) NOT NULL,

    PRIMARY KEY (`MaMonHoc`, `MaMonHocTruoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHUONGTRINHHOC` (
    `MaNganh` VARCHAR(10) NOT NULL,
    `MaMonHoc` VARCHAR(10) NOT NULL,
    `HocKy` VARCHAR(20) NOT NULL,
    `KhoaApDung` VARCHAR(20) NULL,
    `GhiChu` VARCHAR(255) NULL,

    PRIMARY KEY (`MaNganh`, `MaMonHoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MONHOC` ADD CONSTRAINT `MONHOC_MaKhoa_fkey` FOREIGN KEY (`MaKhoa`) REFERENCES `KHOA`(`MaKhoa`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MONHOC` ADD CONSTRAINT `MONHOC_MaLoaiMonHoc_fkey` FOREIGN KEY (`MaLoaiMonHoc`) REFERENCES `LOAIMONHOC`(`MaLoaiMonHoc`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CT_MONHOCTRUOC` ADD CONSTRAINT `CT_MONHOCTRUOC_MaMonHoc_fkey` FOREIGN KEY (`MaMonHoc`) REFERENCES `MONHOC`(`MaMonHoc`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CT_MONHOCTRUOC` ADD CONSTRAINT `CT_MONHOCTRUOC_MaMonHocTruoc_fkey` FOREIGN KEY (`MaMonHocTruoc`) REFERENCES `MONHOC`(`MaMonHoc`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHUONGTRINHHOC` ADD CONSTRAINT `CHUONGTRINHHOC_MaNganh_fkey` FOREIGN KEY (`MaNganh`) REFERENCES `NGANH`(`MaNganh`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHUONGTRINHHOC` ADD CONSTRAINT `CHUONGTRINHHOC_MaMonHoc_fkey` FOREIGN KEY (`MaMonHoc`) REFERENCES `MONHOC`(`MaMonHoc`) ON DELETE RESTRICT ON UPDATE CASCADE;
