-- CreateTable
CREATE TABLE `PHIEUDANGKY` (
    `MaPhieu` VARCHAR(15) NOT NULL,
    `MaSoSinhVien` VARCHAR(15) NOT NULL,
    `MaHKNH` VARCHAR(15) NOT NULL,
    `NgayLapPhieu` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TongTienDK` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `TienMienGiam` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `TongTienPhaiDong` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `SoTienDaDong` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `SoTienConLai` DECIMAL(12, 2) NOT NULL DEFAULT 0,

    INDEX `PHIEUDANGKY_MaHKNH_idx`(`MaHKNH`),
    UNIQUE INDEX `PHIEUDANGKY_MaSoSinhVien_MaHKNH_key`(`MaSoSinhVien`, `MaHKNH`),
    PRIMARY KEY (`MaPhieu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CT_PHIEUDK` (
    `MaPhieuDK` VARCHAR(15) NOT NULL,
    `MaMonHoc` VARCHAR(10) NOT NULL,

    PRIMARY KEY (`MaPhieuDK`, `MaMonHoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHIEUTHUHOCPHI` (
    `MaPhieuThu` VARCHAR(15) NOT NULL,
    `MaPhieuDK` VARCHAR(15) NOT NULL,
    `NgayLapPhieu` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SoTienThu` DECIMAL(12, 2) NOT NULL,

    INDEX `PHIEUTHUHOCPHI_MaPhieuDK_idx`(`MaPhieuDK`),
    PRIMARY KEY (`MaPhieuThu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PHIEUDANGKY` ADD CONSTRAINT `PHIEUDANGKY_MaSoSinhVien_fkey` FOREIGN KEY (`MaSoSinhVien`) REFERENCES `SINHVIEN`(`MaSoSinhVien`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUDANGKY` ADD CONSTRAINT `PHIEUDANGKY_MaHKNH_fkey` FOREIGN KEY (`MaHKNH`) REFERENCES `HOCKYNAMHOC`(`MaHKNH`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CT_PHIEUDK` ADD CONSTRAINT `CT_PHIEUDK_MaPhieuDK_fkey` FOREIGN KEY (`MaPhieuDK`) REFERENCES `PHIEUDANGKY`(`MaPhieu`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CT_PHIEUDK` ADD CONSTRAINT `CT_PHIEUDK_MaMonHoc_fkey` FOREIGN KEY (`MaMonHoc`) REFERENCES `MONHOC`(`MaMonHoc`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUTHUHOCPHI` ADD CONSTRAINT `PHIEUTHUHOCPHI_MaPhieuDK_fkey` FOREIGN KEY (`MaPhieuDK`) REFERENCES `PHIEUDANGKY`(`MaPhieu`) ON DELETE RESTRICT ON UPDATE CASCADE;
