-- CreateTable
CREATE TABLE `SINHVIEN` (
    `MaSoSinhVien` VARCHAR(15) NOT NULL,
    `HoTen` VARCHAR(100) NOT NULL,
    `NgaySinh` DATETIME(3) NULL,
    `GioiTinh` VARCHAR(10) NULL,
    `SoDienThoai` VARCHAR(15) NULL,
    `Email` VARCHAR(100) NULL,
    `MaXa` VARCHAR(10) NULL,
    `MaNganh` VARCHAR(10) NOT NULL,
    `MaDoiTuong` VARCHAR(10) NULL,
    `TinhTrang` VARCHAR(20) NOT NULL DEFAULT 'Đang học',

    UNIQUE INDEX `SINHVIEN_Email_key`(`Email`),
    PRIMARY KEY (`MaSoSinhVien`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NGUOIDUNG` (
    `TenDangNhap` VARCHAR(50) NOT NULL,
    `MatKhau` VARCHAR(255) NOT NULL,
    `VaiTro` ENUM('ADMIN', 'PDT', 'PTC', 'SV') NOT NULL,
    `HoTen` VARCHAR(100) NULL,
    `MaSoSinhVien` VARCHAR(15) NULL,
    `TrangThai` BOOLEAN NOT NULL DEFAULT true,

    UNIQUE INDEX `NGUOIDUNG_MaSoSinhVien_key`(`MaSoSinhVien`),
    PRIMARY KEY (`TenDangNhap`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_MaXa_fkey` FOREIGN KEY (`MaXa`) REFERENCES `XA`(`MaXa`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_MaNganh_fkey` FOREIGN KEY (`MaNganh`) REFERENCES `NGANH`(`MaNganh`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_MaDoiTuong_fkey` FOREIGN KEY (`MaDoiTuong`) REFERENCES `DOITUONGUUTIEN`(`MaDoiTuong`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NGUOIDUNG` ADD CONSTRAINT `NGUOIDUNG_MaSoSinhVien_fkey` FOREIGN KEY (`MaSoSinhVien`) REFERENCES `SINHVIEN`(`MaSoSinhVien`) ON DELETE SET NULL ON UPDATE CASCADE;
